import { spawn } from "node:child_process";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { createWorktree } from "./worktree.js";

const execFileAsync = promisify(execFile);

export interface BatchTask {
  id: string;
  topic: string;
  worktreePath: string;
  branch: string;
}

export interface BatchResult {
  task: BatchTask;
  status: "success" | "failed" | "timeout";
  synthesis?: string;
  prUrl?: string;
  error?: string;
  durationMs: number;
}

export interface BatchOptions {
  count: number;
  topic: string;
  mode?: string;
  models?: string[];
  timeoutMs?: number;
  openPRs?: boolean;
  cwd?: string;
  budgetPerWorker?: number;
}

const DEFAULT_TIMEOUT_MS = 600_000;
const SYNTHESIS_SNIPPET_MAX = 500;

function resolveBinary(): { command: string; prefixArgs: string[] } {
  const override = process.env["CONSILIUM_BIN"];
  if (override && override.length > 0) {
    return { command: override, prefixArgs: [] };
  }
  const argv1 = process.argv[1];
  if (argv1 && argv1.length > 0) {
    return { command: process.execPath, prefixArgs: [argv1] };
  }
  return { command: "consilium", prefixArgs: [] };
}

function buildDebateArgs(
  topic: string,
  mode: string,
  models: string[] | undefined,
  budgetPerWorker: number,
): string[] {
  const args = [
    "debate",
    topic,
    "--mode",
    mode,
    "--output-format",
    "json",
    "--max-budget-usd",
    budgetPerWorker.toFixed(2),
  ];
  if (models && models.length > 0) {
    args.push("--models", models.join(","));
  }
  return args;
}

function extractSynthesis(stdout: string): string | undefined {
  const trimmed = stdout.trim();
  if (!trimmed) return undefined;
  try {
    const parsed = JSON.parse(trimmed) as {
      synthesis?: unknown;
      finalSynthesis?: unknown;
      output?: unknown;
    };
    const synth =
      typeof parsed.synthesis === "string"
        ? parsed.synthesis
        : typeof parsed.finalSynthesis === "string"
          ? parsed.finalSynthesis
          : typeof parsed.output === "string"
            ? parsed.output
            : undefined;
    if (synth) return synth.slice(0, SYNTHESIS_SNIPPET_MAX);
  } catch {
    // not JSON; fall through
  }
  return trimmed.slice(0, SYNTHESIS_SNIPPET_MAX);
}

async function hasGhCli(): Promise<boolean> {
  try {
    await execFileAsync("which", ["gh"]);
    return true;
  } catch {
    return false;
  }
}

async function commitAndOpenPr(
  task: BatchTask,
  topic: string,
): Promise<string | undefined> {
  try {
    await execFileAsync("git", ["add", "-A"], { cwd: task.worktreePath });
  } catch {
    // no-op if nothing to stage
  }
  try {
    await execFileAsync(
      "git",
      ["commit", "-m", `batch: ${topic.slice(0, 60)}`],
      { cwd: task.worktreePath },
    );
  } catch {
    return undefined;
  }
  try {
    await execFileAsync("git", ["push", "-u", "origin", task.branch], {
      cwd: task.worktreePath,
    });
  } catch (err) {
    throw new Error(
      `git push failed: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
  try {
    const { stdout } = await execFileAsync(
      "gh",
      [
        "pr",
        "create",
        "--title",
        `batch: ${topic.slice(0, 60)}`,
        "--body",
        `Auto-generated by /batch on topic: ${topic}`,
      ],
      { cwd: task.worktreePath },
    );
    const match = stdout.match(/https?:\/\/\S+/);
    return match ? match[0] : stdout.trim();
  } catch (err) {
    throw new Error(
      `gh pr create failed: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

async function runOneTask(
  task: BatchTask,
  opts: BatchOptions,
): Promise<BatchResult> {
  const started = Date.now();
  const timeoutMs = opts.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const mode = opts.mode ?? "council";
  const budgetPerWorker = opts.budgetPerWorker ?? 1.0;
  const { command, prefixArgs } = resolveBinary();
  const args = [
    ...prefixArgs,
    ...buildDebateArgs(task.topic, mode, opts.models, budgetPerWorker),
  ];

  return await new Promise<BatchResult>((resolve) => {
    const controller = new AbortController();
    let stdout = "";
    let stderr = "";
    let timedOut = false;
    let settled = false;

    const child = spawn(command, args, {
      cwd: task.worktreePath,
      stdio: ["ignore", "pipe", "pipe"],
      signal: controller.signal,
      env: { ...process.env, CONSILIUM_BG_AGENT: "1" },
    });

    const timer = setTimeout(() => {
      timedOut = true;
      controller.abort();
      try {
        child.kill("SIGKILL");
      } catch {
        // best-effort
      }
      setImmediate(() => {
        finalize({
          task,
          status: "timeout",
          error: `Timed out after ${timeoutMs}ms`,
          durationMs: Date.now() - started,
        });
      });
    }, timeoutMs);

    child.stdout?.on("data", (chunk: Buffer | string) => {
      stdout += typeof chunk === "string" ? chunk : chunk.toString("utf-8");
    });
    child.stderr?.on("data", (chunk: Buffer | string) => {
      stderr += typeof chunk === "string" ? chunk : chunk.toString("utf-8");
    });

    const finalize = (result: BatchResult): void => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(result);
    };

    child.on("error", (err: Error & { code?: string }) => {
      if (timedOut || err.name === "AbortError" || err.code === "ABORT_ERR") {
        finalize({
          task,
          status: "timeout",
          error: `Timed out after ${timeoutMs}ms`,
          durationMs: Date.now() - started,
        });
        return;
      }
      finalize({
        task,
        status: "failed",
        error: err.message,
        durationMs: Date.now() - started,
      });
    });

    child.on("close", (code: number | null) => {
      if (timedOut) {
        finalize({
          task,
          status: "timeout",
          error: `Timed out after ${timeoutMs}ms`,
          durationMs: Date.now() - started,
        });
        return;
      }
      if (code === 0) {
        finalize({
          task,
          status: "success",
          synthesis: extractSynthesis(stdout),
          durationMs: Date.now() - started,
        });
        return;
      }
      const err = stderr.trim() || `exit code ${code ?? "unknown"}`;
      finalize({
        task,
        status: "failed",
        error: err.slice(0, 500),
        durationMs: Date.now() - started,
      });
    });
  });
}

export async function runBatch(opts: BatchOptions): Promise<BatchResult[]> {
  if (!Number.isInteger(opts.count) || opts.count < 1 || opts.count > 30) {
    throw new Error("Batch count must be between 1 and 30");
  }
  const topic = (opts.topic ?? "").trim();
  if (!topic) {
    throw new Error("Batch topic is required");
  }

  const budgetPerWorker = opts.budgetPerWorker ?? 1.0;
  const totalBudget = opts.count * budgetPerWorker;
  console.log(
    `[batch] ${opts.count} worker(s) × $${budgetPerWorker.toFixed(2)}/worker = $${totalBudget.toFixed(2)} max total budget`,
  );

  const cwd = opts.cwd ?? process.cwd();
  const tasks: BatchTask[] = [];
  for (let i = 0; i < opts.count; i++) {
    const branch = `consilium-batch-${Date.now().toString(36)}-${i}`;
    const ref = await createWorktree(branch, { cwd });
    tasks.push({
      id: `batch-${i}`,
      topic,
      worktreePath: ref.path,
      branch: ref.branch,
    });
  }

  const results = await Promise.all(
    tasks.map((task) => runOneTask(task, opts)),
  );

  if (opts.openPRs) {
    const ghAvailable = await hasGhCli();
    if (ghAvailable) {
      for (let i = 0; i < results.length; i++) {
        const r = results[i];
        if (!r || r.status !== "success") continue;
        try {
          const url = await commitAndOpenPr(r.task, topic);
          if (url) r.prUrl = url;
        } catch (err) {
          r.error = err instanceof Error ? err.message : String(err);
        }
      }
    }
  }

  return results;
}
