export type OutputFormat =
  | "markdown"
  | "cursorrules"
  | "claude-md"
  | "json"
  | "text";

const VALID_FORMATS = new Set<OutputFormat>([
  "markdown",
  "cursorrules",
  "claude-md",
  "json",
  "text",
]);

export interface OutputMetadata {
  format: OutputFormat;
  topic: string;
  models: string[];
  mode?: string;
  debateId?: string;
  timestamp?: string;
}

export function isValidOutputFormat(format: string): format is OutputFormat {
  return VALID_FORMATS.has(format as OutputFormat);
}

function slugify(text: string): string {
  let out = "";
  let lastHyphen = false;
  for (const ch of text.toLowerCase()) {
    const code = ch.codePointAt(0)!;
    const isAlnum = (code >= 48 && code <= 57) || (code >= 97 && code <= 122);
    if (isAlnum) {
      out += ch;
      lastHyphen = false;
    } else if (!lastHyphen && out.length > 0) {
      out += "-";
      lastHyphen = true;
    }
  }
  while (out.startsWith("-")) {
    out = out.slice(1);
  }
  while (out.endsWith("-")) {
    out = out.slice(0, -1);
  }
  return out.slice(0, 60);
}

function formatMarkdown(synthesis: string, metadata: OutputMetadata): string {
  const date = metadata.timestamp || new Date().toISOString();
  const models = metadata.models.join(", ");

  const lines: string[] = [
    `# ${metadata.topic}`,
    "",
    "---",
    "",
    `- **Models:** ${models}`,
  ];

  if (metadata.mode) {
    lines.push(`- **Mode:** ${metadata.mode}`);
  }

  if (metadata.debateId) {
    lines.push(`- **Debate ID:** ${metadata.debateId}`);
  }

  lines.push(`- **Date:** ${date}`, "", "---", "", synthesis);

  return lines.join("\n");
}

function formatCursorRules(
  synthesis: string,
  metadata: OutputMetadata,
): string {
  const rules = synthesis
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

  const lines: string[] = [
    "# Generated by Consilium AI Council",
    `# Topic: ${metadata.topic}`,
    `# Models: ${metadata.models.join(", ")}`,
    "",
  ];

  let ruleNumber = 1;
  for (const rule of rules) {
    lines.push(`## Rule ${ruleNumber}`, "", rule, "");
    ruleNumber++;
  }

  return lines.join("\n");
}

function formatClaudeMd(synthesis: string, metadata: OutputMetadata): string {
  const paragraphs = synthesis
    .split("\n\n")
    .map((p) => p.trim())
    .filter((p) => p.length > 0);

  const third = Math.max(1, Math.ceil(paragraphs.length / 3));
  const decisions = paragraphs.slice(0, third);
  const guidelines = paragraphs.slice(third, third * 2);
  const context = paragraphs.slice(third * 2);

  const lines: string[] = [
    "# Generated by Consilium AI Council",
    "",
    `> Topic: ${metadata.topic}`,
    `> Models: ${metadata.models.join(", ")}`,
    "",
    "## Project Decisions",
    "",
    ...decisions.flatMap((p) => [p, ""]),
    "## Guidelines",
    "",
    ...guidelines.flatMap((p) => [p, ""]),
    "## Context",
    "",
    ...context.flatMap((p) => [p, ""]),
  ];

  return lines.join("\n").trimEnd() + "\n";
}

function formatJson(synthesis: string, metadata: OutputMetadata): string {
  const obj = {
    topic: metadata.topic,
    models: metadata.models,
    mode: metadata.mode ?? null,
    synthesis,
    timestamp: metadata.timestamp || new Date().toISOString(),
    debateId: metadata.debateId ?? null,
  };

  return JSON.stringify(obj, null, 2);
}

export function formatOutput(
  synthesis: string,
  metadata: OutputMetadata,
): string {
  switch (metadata.format) {
    case "markdown":
      return formatMarkdown(synthesis, metadata);
    case "cursorrules":
      return formatCursorRules(synthesis, metadata);
    case "claude-md":
      return formatClaudeMd(synthesis, metadata);
    case "json":
      return formatJson(synthesis, metadata);
    case "text":
    default:
      return synthesis;
  }
}

export function getFileExtension(format: OutputFormat): string {
  switch (format) {
    case "markdown":
      return ".md";
    case "cursorrules":
      return "";
    case "claude-md":
      return ".md";
    case "json":
      return ".json";
    case "text":
      return ".txt";
  }
}

export function getDefaultFilename(
  format: OutputFormat,
  topic: string,
): string {
  const slug = slugify(topic);

  switch (format) {
    case "markdown":
      return `${slug}.md`;
    case "cursorrules":
      return ".cursorrules";
    case "claude-md":
      return "CLAUDE.md";
    case "json":
      return `${slug}.json`;
    case "text":
      return `${slug}.txt`;
  }
}
